### ISSUE TITLE
Unable to import a table from Oracle when the given table has null value in some of the columns

### ISSUE THREAD

**Issue by gkswamyps** [senips/mintleaf#1]
Thanks for this Great tool which is helping me to import Data from Oracle to H2.

however there is a small issue in this tool. While importing a Table from Oracle to H2,  when the table columns have null value, the import fails.

So, this issue has limit the usage of Data import of all columns, when the values for columns have null value.

Thanks,
Krishna

**Comment by senips** [comment]
Need to return db 'NULL' if a column value is null so it got fixed now. So if you change your POM version to 1.8.14 should fix your issue.

**Comment by gkswamyps** [comment]
Thanks it works now. I did a unit testing to import a table that has null value in few columns
